"""Add content field

Revision ID: ca09d903b3b1
Revises: 48f8d118ad50
Create Date: 2026-05-22 12:43:58.987710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca09d903b3b1'
down_revision = '48f8d118ad50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('emergency_phone', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('emergency_email', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('is_pro', sa.Boolean(), nullable=True))
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.create_unique_constraint(None, ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=80),
               nullable=True)
        batch_op.drop_column('is_pro')
        batch_op.drop_column('emergency_email')
        batch_op.drop_column('emergency_phone')
        batch_op.drop_column('emergency_name')

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('content')

    # ### end Alembic commands ###
